### ISSUE TITLE
Module not found after installing with npm 

### ISSUE THREAD

**Issue by platocrat** [ptpaterson/faunadb-graphql-schema-loader#1]
I get the following error on importing this library after installing with `npm`.

<img width="587" alt="Screen Shot 2020-09-11 at 12 02 22 PM" src="https://user-images.githubusercontent.com/37757724/92953058-a7d65e80-f426-11ea-90ce-3904fd151252.png">

This is what my code looks like:

```javascript
import { importSchema } from 'faunadb-graphql-schema-loader'

const secretKey = process.env.FAUNADB_ADMIN_KEY

const schema = `
  type Crypto {
    id: Int!
    name: String!
    symbol: String!
    slug: String!
    num_market_pairs: Int
    date_added: String
    tags: [String]
    circulating_supply: Float
    total_supply: Float
    cmc_rank: Int
    last_updated: String
  }

  type Query {
    cryptos: [Crypto!]
    crypto(name: String): Crypto
  }
`

importSchema(secretKey, schema).then(res => console.log(res))
```

I also tried using `require` to import, but that resulted in the same error.

**Comment by ptpaterson** [comment]
Thank you for catching!

This was because index.js was not properly exported.  I added the "main" field to the package.json, and published the patch to npm.

Please upgrade to 0.1.1 and it should work now.
