### ISSUE TITLE
Rendering Response message on browser

### ISSUE THREAD

**Issue by platocrat** [ptpaterson/faunadb-graphql-schema-loader#2]
# Render helpful successful import message on client
I can run my `importSchema` API successfully server-side and receive this helpful message when I `console.log()` the response:

```
Schema imported successfully.
Use the following HTTP header to connect to the FaunaDB GraphQL API:
{ "Authorization": "Bearer <SECRET_KEY" }
```

Perhaps this is forbidden due to potential security issues regarding the secret key, but I've been trying to render this message on the browser. 
I can successfully receive the Response object from my API endpoint; however, when I `console.log()` it, what is returned is not the helpful message, but instead, an entire Response object which is void of such a helpful message. 

Is there some way to replicate this "Schema imported successfully." message on the client/browser?

## More context
Currently, I've been experimenting in trying to render this message on the browser using a hook like the following:

```javascript
function useImportSchema() {
  const [schema, setSchema] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch('api/importSchema')
      .then(data => data.body.getReader().read())
      .then(text => {
        setSchema(text)
        setLoading(false)
      })
  }, [])

  return [schema, loading]
}
```

I've tried `.json()`, `text()`, and `.body` response objects, and none seem to be returning the desired message (excluding the full Response object returned when using `body`.

Any possible workarounds to still provide a success message to the user on the browser?

**Comment by ptpaterson** [comment]
Looks like there are a few things coming together, including the response from fauna's api, your API function, and the browser `fetch` api.

I've not tried to use this proxied through an API before so will need to try a couple of things and get back!

**Comment by ptpaterson** [comment]
I've had a chance to tinker today.  I can confirm that the result of `importSchema` function is a plain javascript string.

I am guessing that this is something in the API function.  You can share if you are okay with that and I will try to work it out with you.  I am going to close this though.  

Sorry that it took this long to respond, I hope that you've got things working by now.

**Comment by platocrat** [comment]
No worries. I did get the `importSchema` function to work, but never figured out a way to display similar helper text on the front-end if importing a schema was successful or not (if not, display text that says so).
